//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::{
    chain_id::Entity as ChainId, last_processed_version::Entity as LastProcessedVersion,
    pixel_attribution::Entity as PixelAttribution,
};
