//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

pub use super::chain_id::Entity as ChainId;
pub use super::last_processed_version::Entity as LastProcessedVersion;
pub use super::pixel_attribution::Entity as PixelAttribution;
